sudo: required
services:
    - docker

before_install:
    - docker build -t alo42/react-test -f ./client/Dockerfile.dev ./client

scipts:
    - docker run -e CI=true alo42/react-test npm test

after_successs:
    - docker build -t alo42/multi-client ./client
    - docker build -t alo42/multi-worker ./worker
    - docker build -t alo42/multi-nginx ./nginx
    - docker build -t alo42/multi-server ./server
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
    - docker push alo42/multi-client
    - docker push alo42/multi-worker
    - docker push alo42/multi-nginx
    - docker push alo42/multi-server